version: '3'

services:
  derive_1:
    build:
      context: .
      dockerfile: Dockerfile
    command:  "npm run stress-test-derive 300"
  derive_2:
    build:
      context: .
      dockerfile: Dockerfile
    command:  "npm run stress-test-derive 300"
  derive_3:
    build:
      context: .
      dockerfile: Dockerfile
    command:  "npm run stress-test-derive 300"
  derive_4:
    build:
      context: .
      dockerfile: Dockerfile
    command:  "npm run stress-test-derive 300"
  sign_1:
    build:
      context: .
      dockerfile: Dockerfile
    command:  "npm run stress-test-sign 300"
  sign_2:
    build:
      context: .
      dockerfile: Dockerfile
    command:  "npm run stress-test-sign 300"
